#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Step 5: Merge per-sample gene-level abundance tables and attach functional labels.

This script is designed for the BileActome non-redundant gene catalog workflow.
It merges the per-sample RPKM/abundance tables generated by Step 4 and joins
BileActome functional annotations from gene_to_function.tsv.

Expected Step 4 abundance file format:
    gene_id<TAB>sample_abundance
or
    Gene<TAB>sample_abundance

Expected function map format:
    gene_id<TAB>function

Output format:
    gene_id | function | sample1 | sample2 | ...

Example:
    python scripts/step5_merge_abundance_with_function.py \
      --abundance-dir /path/to/abundance \
      --function-map /path/to/gene_to_function.tsv \
      --out-xlsx /path/to/abundance_merged_with_function.xlsx
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List, Optional

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Merge per-sample gene-level abundance files and attach BileActome function labels."
    )
    parser.add_argument(
        "--abundance-dir",
        required=True,
        help="Directory containing per-sample abundance TSV files generated by Step 4."
    )
    parser.add_argument(
        "--function-map",
        required=True,
        help="TSV file mapping gene_id to function, typically generated by Step 2."
    )
    parser.add_argument(
        "--out-xlsx",
        required=True,
        help="Output Excel file, e.g. abundance_merged_with_function.xlsx."
    )
    parser.add_argument(
        "--out-tsv",
        default=None,
        help="Optional output TSV file with the same merged table."
    )
    parser.add_argument(
        "--pattern",
        default="*_rpkm.tsv",
        help="Glob pattern for abundance files. Default: '*_rpkm.tsv'."
    )
    parser.add_argument(
        "--sample-suffix",
        default="_rpkm",
        help="Suffix to remove from abundance file stem to obtain sample name. Default: '_rpkm'."
    )
    parser.add_argument(
        "--gene-col-candidates",
        default="gene_id,Gene,GeneID,gene,ID",
        help="Comma-separated candidate column names for gene IDs in abundance tables."
    )
    parser.add_argument(
        "--join",
        choices=["inner", "left", "outer"],
        default="inner",
        help=(
            "How to join function annotations with abundance matrix. "
            "inner keeps annotated genes only; left keeps all genes in function map; "
            "outer keeps all genes from both. Default: inner."
        )
    )
    parser.add_argument(
        "--fillna",
        type=float,
        default=0.0,
        help="Value used to fill missing abundance values. Default: 0."
    )
    parser.add_argument(
        "--duplicate-policy",
        choices=["first", "all"],
        default="first",
        help=(
            "How to handle genes mapped to multiple functions. "
            "first keeps the first gene-function pair; all keeps all gene-function pairs and may duplicate gene rows. "
            "Default: first."
        )
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing output files."
    )
    return parser.parse_args()


def ensure_overwrite(path: Optional[Path], force: bool) -> None:
    if path is None:
        return
    if path.exists() and not force:
        raise FileExistsError(f"Output exists: {path}. Use --force to overwrite.")


def read_function_map(path: Path, duplicate_policy: str) -> pd.DataFrame:
    if not path.is_file():
        raise FileNotFoundError(f"Function map not found: {path}")

    # Header is expected, but this also works for a simple two-column TSV.
    fmap = pd.read_csv(path, sep="\t", dtype=str)
    if fmap.shape[1] < 2:
        raise ValueError("Function map must contain at least two columns: gene_id and function.")

    # Normalize common column-name variants.
    cols = list(fmap.columns)
    gene_col = "gene_id" if "gene_id" in cols else cols[0]
    func_col = "function" if "function" in cols else cols[1]
    fmap = fmap[[gene_col, func_col]].rename(columns={gene_col: "gene_id", func_col: "function"})
    fmap = fmap.dropna(subset=["gene_id", "function"])
    fmap["gene_id"] = fmap["gene_id"].astype(str)
    fmap["function"] = fmap["function"].astype(str)

    before = len(fmap)
    if duplicate_policy == "first":
        fmap = fmap.drop_duplicates(subset=["gene_id"], keep="first")
    else:
        fmap = fmap.drop_duplicates(subset=["gene_id", "function"], keep="first")
    after = len(fmap)

    if before != after:
        print(f"[INFO] Removed {before - after} duplicated mapping rows using policy: {duplicate_policy}")

    return fmap.set_index("gene_id")


def read_abundance_file(path: Path, sample_suffix: str, gene_col_candidates: List[str]) -> pd.DataFrame:
    df = pd.read_csv(path, sep="\t")
    if df.shape[1] < 2:
        raise ValueError(f"Abundance file has fewer than two columns: {path}")

    gene_col = None
    for c in gene_col_candidates:
        if c in df.columns:
            gene_col = c
            break
    if gene_col is None:
        # Fallback: use first column as gene ID.
        gene_col = df.columns[0]

    value_cols = [c for c in df.columns if c != gene_col]
    if len(value_cols) < 1:
        raise ValueError(f"No abundance column found in: {path}")

    # Step 4 normally writes exactly one abundance column. If multiple exist,
    # take the first numeric-like column after the gene column.
    abundance_col = value_cols[0]

    sample_name = path.stem
    if sample_suffix and sample_name.endswith(sample_suffix):
        sample_name = sample_name[: -len(sample_suffix)]

    out = df[[gene_col, abundance_col]].copy()
    out = out.rename(columns={gene_col: "gene_id", abundance_col: sample_name})
    out["gene_id"] = out["gene_id"].astype(str)
    out[sample_name] = pd.to_numeric(out[sample_name], errors="coerce").fillna(0.0)

    # If a gene appears multiple times in a sample file, sum its abundance.
    out = out.groupby("gene_id", as_index=True)[sample_name].sum().to_frame()
    return out


def main() -> int:
    args = parse_args()

    abundance_dir = Path(args.abundance_dir)
    function_map = Path(args.function_map)
    out_xlsx = Path(args.out_xlsx)
    out_tsv = Path(args.out_tsv) if args.out_tsv else None

    if not abundance_dir.is_dir():
        raise NotADirectoryError(f"Abundance directory not found: {abundance_dir}")

    ensure_overwrite(out_xlsx, args.force)
    ensure_overwrite(out_tsv, args.force)
    out_xlsx.parent.mkdir(parents=True, exist_ok=True)
    if out_tsv is not None:
        out_tsv.parent.mkdir(parents=True, exist_ok=True)

    print(f"[INFO] Reading function map: {function_map}")
    function_df = read_function_map(function_map, args.duplicate_policy)
    print(f"[INFO] Function-mapped genes: {function_df.shape[0]}")

    files = sorted(abundance_dir.glob(args.pattern))
    if not files:
        raise FileNotFoundError(f"No abundance files matched {args.pattern!r} in {abundance_dir}")

    gene_col_candidates = [x.strip() for x in args.gene_col_candidates.split(",") if x.strip()]
    all_dfs = []
    for path in files:
        print(f"[INFO] Reading abundance file: {path.name}")
        all_dfs.append(read_abundance_file(path, args.sample_suffix, gene_col_candidates))

    print(f"[INFO] Merging {len(all_dfs)} sample abundance tables")
    abundance = pd.concat(all_dfs, axis=1).fillna(args.fillna)

    # Join function labels to the gene-level abundance matrix.
    merged = function_df.join(abundance, how=args.join)
    sample_cols = [c for c in merged.columns if c != "function"]
    if sample_cols:
        merged[sample_cols] = merged[sample_cols].fillna(args.fillna)

    merged = merged.reset_index().rename(columns={"index": "gene_id"})

    # Put columns in a stable order.
    ordered_cols = ["gene_id", "function"] + [c for c in merged.columns if c not in ("gene_id", "function")]
    merged = merged[ordered_cols]

    print(f"[INFO] Output rows: {merged.shape[0]}, sample columns: {len(ordered_cols) - 2}")
    print(f"[INFO] Writing Excel: {out_xlsx}")
    with pd.ExcelWriter(out_xlsx, engine="openpyxl") as writer:
        merged.to_excel(writer, index=False, sheet_name="GeneAbundance")

    if out_tsv is not None:
        print(f"[INFO] Writing TSV: {out_tsv}")
        merged.to_csv(out_tsv, sep="\t", index=False)

    print("[OK] Step 5 completed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
