#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Step 6: Aggregate gene-level abundance to function-level abundance,
then compute within-sample relative abundance and CLR-transformed matrices.

Input
-----
A table generated by Step 5, typically with columns:
    gene_id | function | sample_1 | sample_2 | ...

Outputs
-------
1) Function-sum matrix: function-level summed abundance per sample.
2) Relative-abundance matrix: each sample column sums to 1 across functions.
3) CLR matrix: centered log-ratio transform performed column-wise, i.e.
   within each sample across functions.

Example
-------
python scripts/step6_function_abundance_transform.py \
  --in-table results/abundance_merged_with_function.xlsx \
  --out-func results/FunctionSum_matrix.xlsx \
  --out-rel results/Relative_abundance_matrix.xlsx \
  --out-clr results/CLR_matrix.xlsx \
  --force
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Optional, Union

import numpy as np
import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Aggregate gene-level abundance with function annotations to function-level "
            "sum, relative abundance, and CLR matrices."
        )
    )
    parser.add_argument(
        "--in-table",
        "--in_xlsx",
        dest="in_table",
        required=True,
        help="Input Step5 table. Supported formats: .xlsx, .xls, .tsv, .txt, .csv.",
    )
    parser.add_argument(
        "--out-func",
        "--out_func_xlsx",
        dest="out_func",
        required=True,
        help="Output function-level summed abundance matrix. Extension controls format (.xlsx/.tsv/.csv).",
    )
    parser.add_argument(
        "--out-rel",
        "--out_rel_xlsx",
        dest="out_rel",
        required=True,
        help="Output function-level relative abundance matrix. Extension controls format (.xlsx/.tsv/.csv).",
    )
    parser.add_argument(
        "--out-clr",
        "--out_clr_xlsx",
        dest="out_clr",
        required=True,
        help="Output function-level CLR matrix. Extension controls format (.xlsx/.tsv/.csv).",
    )
    parser.add_argument(
        "--sheet",
        default="0",
        help=(
            "Excel sheet name or index for --in-table if Excel is used. "
            "Default: 0, the first sheet."
        ),
    )
    parser.add_argument(
        "--gene-col",
        default="gene_id",
        help="Gene identifier column name in the input table. Default: gene_id.",
    )
    parser.add_argument(
        "--function-col",
        default="function",
        help="Function/family annotation column name in the input table. Default: function.",
    )
    parser.add_argument(
        "--sample-cols",
        default=None,
        help=(
            "Optional comma-separated sample columns. If omitted, all columns except "
            "gene/function columns are treated as sample abundance columns."
        ),
    )
    parser.add_argument(
        "--epsilon",
        type=float,
        default=1e-12,
        help="Small pseudocount added to relative abundance before CLR. Default: 1e-12.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite output files if they already exist.",
    )
    return parser.parse_args()


def parse_sheet_arg(sheet: Optional[str]) -> Union[int, str, None]:
    """Convert numeric sheet strings to integer indices."""
    if sheet is None or str(sheet).lower() in {"none", "null"}:
        return 0
    sheet = str(sheet).strip()
    if sheet.isdigit():
        return int(sheet)
    return sheet


def read_table(path: Path, sheet: Union[int, str, None]) -> pd.DataFrame:
    """Read xlsx/xls/tsv/csv into a DataFrame."""
    suffix = path.suffix.lower()
    if suffix in {".xlsx", ".xls"}:
        obj = pd.read_excel(path, sheet_name=sheet)
        # pandas returns a dict when sheet_name=None; take the first sheet defensively.
        if isinstance(obj, dict):
            return next(iter(obj.values()))
        return obj
    if suffix in {".tsv", ".txt"}:
        return pd.read_csv(path, sep="\t")
    if suffix == ".csv":
        return pd.read_csv(path)
    raise ValueError(f"Unsupported input format: {path}. Use .xlsx, .xls, .tsv, .txt, or .csv.")


def write_table(df: pd.DataFrame, path: Path, sheet_name: str) -> None:
    """Write DataFrame to xlsx/tsv/csv depending on extension."""
    path.parent.mkdir(parents=True, exist_ok=True)
    suffix = path.suffix.lower()
    if suffix in {".xlsx", ".xls"}:
        with pd.ExcelWriter(path, engine="openpyxl") as writer:
            df.to_excel(writer, index=False, sheet_name=sheet_name)
    elif suffix in {".tsv", ".txt"}:
        df.to_csv(path, sep="\t", index=False)
    elif suffix == ".csv":
        df.to_csv(path, index=False)
    else:
        raise ValueError(f"Unsupported output format: {path}. Use .xlsx, .tsv, or .csv.")


def check_overwrite(paths: list[Path], force: bool) -> None:
    existing = [str(p) for p in paths if p.exists() and not force]
    if existing:
        raise FileExistsError(
            "Output file(s) already exist. Use --force to overwrite:\n" + "\n".join(existing)
        )


def clr_transform(rel_abundance: pd.DataFrame) -> pd.DataFrame:
    """
    Column-wise CLR transform.

    Rows are functions and columns are samples. For each sample column, subtract
    the mean log abundance across all functions.
    """
    logp = np.log(rel_abundance)
    geometric_mean_log = logp.mean(axis=0)
    return logp.sub(geometric_mean_log, axis=1)


def main() -> None:
    args = parse_args()

    in_table = Path(args.in_table)
    out_func = Path(args.out_func)
    out_rel = Path(args.out_rel)
    out_clr = Path(args.out_clr)

    if not in_table.exists():
        raise FileNotFoundError(f"Input table not found: {in_table}")
    if args.epsilon <= 0:
        raise ValueError("--epsilon must be > 0 for CLR transformation.")

    check_overwrite([out_func, out_rel, out_clr], args.force)

    df = read_table(in_table, parse_sheet_arg(args.sheet))

    required_cols = {args.gene_col, args.function_col}
    missing = required_cols - set(df.columns)
    if missing:
        raise ValueError(
            f"Missing required column(s): {sorted(missing)}. "
            f"Available columns: {list(df.columns)}"
        )

    if args.sample_cols:
        sample_cols = [c.strip() for c in args.sample_cols.split(",") if c.strip()]
        missing_samples = [c for c in sample_cols if c not in df.columns]
        if missing_samples:
            raise ValueError(f"Sample columns not found: {missing_samples}")
    else:
        sample_cols = [c for c in df.columns if c not in {args.gene_col, args.function_col}]

    if not sample_cols:
        raise ValueError("No sample abundance columns found.")

    # Convert sample columns to numeric abundance values.
    abundance = df[sample_cols].apply(pd.to_numeric, errors="coerce")
    if abundance.isna().any().any():
        bad_cols = abundance.columns[abundance.isna().any()].tolist()
        raise ValueError(
            "Non-numeric or missing values detected in sample columns. "
            f"Problematic columns: {bad_cols}"
        )

    clean = pd.concat([df[[args.function_col]], abundance], axis=1)

    # Function-level summed abundance: rows = functions, columns = samples.
    func_sum = clean.groupby(args.function_col, as_index=True)[sample_cols].sum()
    func_sum_out = func_sum.reset_index()
    write_table(func_sum_out, out_func, sheet_name="FunctionSum")

    # Within-sample relative abundance. Each sample column sums to 1 across functions.
    col_sums = func_sum.sum(axis=0)
    zero_sum_cols = col_sums[col_sums == 0].index.tolist()
    if zero_sum_cols:
        raise ValueError(
            "The following sample columns sum to 0 at function level and cannot be normalized: "
            f"{zero_sum_cols}"
        )
    rel = func_sum.div(col_sums, axis=1)
    write_table(rel.reset_index(), out_rel, sheet_name="RelativeAbundance")

    # CLR is computed column-wise (within sample) after adding a small pseudocount.
    clr = clr_transform(rel + args.epsilon)
    write_table(clr.reset_index(), out_clr, sheet_name="CLR")

    print("[OK] Step6 completed.")
    print(f"  Functions: {func_sum.shape[0]}")
    print(f"  Samples:   {func_sum.shape[1]}")
    print(f"  Function-sum matrix:       {out_func}")
    print(f"  Relative abundance matrix: {out_rel}")
    print(f"  CLR matrix:                {out_clr}")
    print("  Note: CLR was performed column-wise, i.e. within each sample across functions.")


if __name__ == "__main__":
    main()
