#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Step 4: Calculate gene-level abundance from Bowtie2 SAM alignments.

This script counts reads mapped to each target CDS and calculates RPKM:

    RPKM = mapped_reads_to_gene / (gene_length_kb * total_mapped_reads_million)

Inputs:
  1. SAM files generated by Bowtie2 against target_cds.fa
  2. target_cds.fa from Step 2

Outputs:
  1. One TSV file per sample: gene_id + RPKM
  2. A CDS length table

Typical usage:
  python scripts/step4_abundance_calc.py \
    --sam-dir /path/to/bowtie2_map \
    --cds-fasta /path/to/target_cds.fa \
    --out-dir /path/to/abundance \
    --gene-length-file /path/to/target_cds_length.tsv
"""

import argparse
import gzip
from collections import defaultdict
from pathlib import Path
from typing import Dict, Tuple

import pandas as pd
from Bio import SeqIO


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Calculate gene-level RPKM abundance from Bowtie2 SAM files."
    )
    parser.add_argument(
        "--sam-dir",
        required=True,
        help="Directory containing SAM files from Step 3."
    )
    parser.add_argument(
        "--cds-fasta",
        required=True,
        help="Target CDS FASTA file from Step 2, e.g. target_cds.fa."
    )
    parser.add_argument(
        "--out-dir",
        required=True,
        help="Output directory for per-sample RPKM tables."
    )
    parser.add_argument(
        "--gene-length-file",
        default=None,
        help=(
            "Output path for the gene length table. Default: "
            "<out-dir>/target_cds_length.tsv"
        )
    )
    parser.add_argument(
        "--sam-pattern",
        default="*.sam",
        help="Glob pattern for SAM files in --sam-dir. Default: *.sam"
    )
    parser.add_argument(
        "--sample-strip",
        default=".nohost",
        help=(
            "Substring removed from sample names after taking the SAM file stem. "
            "Default: .nohost. Use '' to disable."
        )
    )
    parser.add_argument(
        "--id-regex",
        default=None,
        help=(
            "Optional Python regular expression with one capturing group to normalize "
            "CDS IDs, e.g. '^([^\\s|]+)'. Usually not needed if FASTA IDs match SAM RNAME."
        )
    )
    parser.add_argument(
        "--include-secondary",
        action="store_true",
        help=(
            "Include secondary/supplementary alignments. By default, alignments with "
            "SAM flag 0x100 or 0x800 are ignored."
        )
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing per-sample RPKM output files."
    )
    return parser.parse_args()


def open_text(path: Path):
    """Open plain text or gzipped text files."""
    if str(path).endswith(".gz"):
        return gzip.open(path, "rt")
    return open(path, "r")


def normalize_id(seq_id: str, id_regex: str = None) -> str:
    """Optionally normalize a sequence ID using a regex capturing group."""
    if not id_regex:
        return seq_id
    import re
    m = re.search(id_regex, seq_id)
    return m.group(1) if m else seq_id


def read_gene_lengths(cds_fasta: Path, id_regex: str = None) -> Dict[str, int]:
    """Read CDS FASTA and return a gene_id -> length dictionary."""
    gene_lengths: Dict[str, int] = {}
    with open_text(cds_fasta) as handle:
        for record in SeqIO.parse(handle, "fasta"):
            gene_id = normalize_id(record.id, id_regex)
            if gene_id in gene_lengths:
                raise ValueError(
                    f"Duplicated CDS ID after normalization: {gene_id}. "
                    "Please check --id-regex or FASTA headers."
                )
            gene_lengths[gene_id] = len(record.seq)
    if not gene_lengths:
        raise ValueError(f"No CDS records found in: {cds_fasta}")
    return gene_lengths


def write_gene_lengths(gene_lengths: Dict[str, int], out_file: Path) -> None:
    out_file.parent.mkdir(parents=True, exist_ok=True)
    with open(out_file, "w") as out:
        out.write("gene_id\tlength_bp\n")
        for gene_id, length in gene_lengths.items():
            out.write(f"{gene_id}\t{length}\n")


def parse_sam(
    sam_path: Path,
    include_secondary: bool = False
) -> Tuple[Dict[str, int], int]:
    """
    Parse a SAM file and count mapped alignments per reference gene.

    Notes:
      - Unmapped reads have RNAME='*' and are ignored.
      - Secondary (0x100) and supplementary (0x800) alignments are ignored by default.
      - total_mapped_reads is the number of retained mapped alignment records.
    """
    read_counts: Dict[str, int] = defaultdict(int)
    total_mapped_reads = 0

    with open_text(sam_path) as handle:
        for line in handle:
            if not line or line.startswith("@"):
                continue
            fields = line.rstrip("\n").split("\t")
            if len(fields) < 3:
                continue

            try:
                flag = int(fields[1])
            except ValueError:
                continue

            # Skip secondary/supplementary alignments by default to reduce double counting.
            if not include_secondary and (flag & 0x100 or flag & 0x800):
                continue

            gene_id = fields[2]
            if gene_id == "*":
                continue

            read_counts[gene_id] += 1
            total_mapped_reads += 1

    return read_counts, total_mapped_reads


def sample_name_from_sam(sam_file: Path, sample_strip: str) -> str:
    sample = sam_file.name
    if sample.endswith(".sam.gz"):
        sample = sample[:-7]
    elif sample.endswith(".sam"):
        sample = sample[:-4]
    else:
        sample = sam_file.stem
    if sample_strip:
        sample = sample.replace(sample_strip, "")
    return sample


def calculate_rpkm(
    gene_lengths: Dict[str, int],
    read_counts: Dict[str, int],
    total_mapped_reads: int,
    sample: str
) -> pd.DataFrame:
    rows = []
    total_mapped_million = total_mapped_reads / 1e6

    for gene_id, length_bp in gene_lengths.items():
        count = read_counts.get(gene_id, 0)
        length_kb = length_bp / 1000.0
        if total_mapped_reads > 0 and length_kb > 0:
            rpkm = count / (length_kb * total_mapped_million)
        else:
            rpkm = 0.0
        rows.append((gene_id, rpkm))

    return pd.DataFrame(rows, columns=["Gene", sample]).set_index("Gene")


def main() -> None:
    args = parse_args()

    sam_dir = Path(args.sam_dir).resolve()
    cds_fasta = Path(args.cds_fasta).resolve()
    out_dir = Path(args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    if not sam_dir.is_dir():
        raise FileNotFoundError(f"SAM directory not found: {sam_dir}")
    if not cds_fasta.is_file() or cds_fasta.stat().st_size == 0:
        raise FileNotFoundError(f"CDS FASTA not found or empty: {cds_fasta}")

    gene_length_file = (
        Path(args.gene_length_file).resolve()
        if args.gene_length_file
        else out_dir / "target_cds_length.tsv"
    )

    print(f"Reading CDS lengths from: {cds_fasta}")
    gene_lengths = read_gene_lengths(cds_fasta, args.id_regex)
    write_gene_lengths(gene_lengths, gene_length_file)
    print(f"Wrote gene length table: {gene_length_file}")
    print(f"Total target CDSs: {len(gene_lengths)}")

    sam_files = sorted(sam_dir.glob(args.sam_pattern))
    if not sam_files:
        raise FileNotFoundError(
            f"No SAM files matched pattern '{args.sam_pattern}' in {sam_dir}"
        )

    print(f"Found {len(sam_files)} SAM file(s).")

    for sam_file in sam_files:
        sample = sample_name_from_sam(sam_file, args.sample_strip)
        output_path = out_dir / f"{sample}_rpkm.tsv"
        done_flag = out_dir / f"{sample}_rpkm.done"
        tmp_path = out_dir / f"{sample}_rpkm.tsv.tmp"

        if not args.force and done_flag.exists() and output_path.is_file() and output_path.stat().st_size > 0:
            print(f"Skip existing sample: {sample}")
            continue
        if not args.force and output_path.is_file() and output_path.stat().st_size > 0:
            print(f"Skip existing output: {sample}")
            done_flag.touch()
            continue

        print(f"Calculating RPKM for sample: {sample}")
        read_counts, total_reads = parse_sam(
            sam_file,
            include_secondary=args.include_secondary
        )
        print(f"  retained mapped alignment records: {total_reads}")

        df = calculate_rpkm(gene_lengths, read_counts, total_reads, sample)
        df.to_csv(tmp_path, sep="\t")
        tmp_path.replace(output_path)
        done_flag.touch()

        print(f"  done: {output_path}")

    print(f"All per-sample abundance tables written to: {out_dir}")


if __name__ == "__main__":
    main()
