#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Step 2: extract CDS sequences matched by BileActome HMM annotation.

This script parses HMMER domtblout files generated by Step 1 (hmmscan by
default), collects matched protein/gene IDs and their assigned HMM families,
then extracts the corresponding nucleotide CDS sequences from a non-redundant
CDS FASTA file.

Typical inputs
--------------
1. HMMER domtblout files from Step 1, e.g. *_hmmscan.txt
2. Non-redundant CDS FASTA file whose sequence IDs correspond to the protein IDs
   used in Step 1

Outputs
-------
1. target_cds.fa: CDS sequences matched to any HMM family
2. gene_to_function.tsv: mapping table with columns gene_id and function
3. missing_ids.txt: matched IDs not found in the CDS FASTA, useful for checking
   protein/CDS ID compatibility
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, Iterable, Optional, Set, Tuple

from Bio import SeqIO


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract CDS sequences and gene-to-function mapping from HMMER domtblout results."
    )
    parser.add_argument(
        "--hmm-result-dir",
        required=True,
        help="Directory containing HMMER domtblout files from Step 1, e.g. *_hmmscan.txt.",
    )
    parser.add_argument(
        "--cds-fasta",
        required=True,
        help="Non-redundant CDS FASTA file. FASTA IDs should match protein/query IDs from Step 1.",
    )
    parser.add_argument(
        "--out-cds",
        required=True,
        help="Output FASTA file containing CDS sequences matched to HMM families.",
    )
    parser.add_argument(
        "--out-map",
        required=True,
        help="Output TSV file mapping gene_id to function.",
    )
    parser.add_argument(
        "--out-missing",
        default=None,
        help="Optional output text file for matched IDs not found in CDS FASTA. Default: <out-map>.missing_ids.txt",
    )
    parser.add_argument(
        "--pattern",
        default="*_hmmscan.txt",
        help="Glob pattern for HMMER result files. Default: *_hmmscan.txt",
    )
    parser.add_argument(
        "--strip-suffix",
        default="_hmmscan.txt",
        help="Suffix to remove from HMM result filenames to obtain function names. Default: _hmmscan.txt",
    )
    parser.add_argument(
        "--hmmer-program",
        choices=["hmmscan", "hmmsearch"],
        default="hmmscan",
        help=(
            "HMMER program used to generate domtblout. For hmmscan, the query name "
            "(field 4) is the protein ID. For hmmsearch, the target name (field 1) is the protein ID. "
            "Default: hmmscan"
        ),
    )
    parser.add_argument(
        "--id-regex",
        default=None,
        help=(
            "Optional Python regex with one capturing group to normalize IDs from both HMM output and FASTA. "
            "Example: '^([^|]+)' keeps text before the first pipe. Default: exact SeqIO ID."
        ),
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing output files if present.",
    )
    return parser.parse_args()


def normalize_id(seq_id: str, id_regex: Optional[str]) -> str:
    """Normalize sequence IDs using an optional regex with one capturing group."""
    if id_regex is None:
        return seq_id
    match = re.search(id_regex, seq_id)
    if not match:
        return seq_id
    if match.groups():
        return match.group(1)
    return match.group(0)


def function_name_from_file(path: Path, strip_suffix: str) -> str:
    """Convert a result filename into a function/family name."""
    name = path.name
    if strip_suffix and name.endswith(strip_suffix):
        return name[: -len(strip_suffix)]
    return path.stem


def parse_domtblout(
    result_files: Iterable[Path],
    strip_suffix: str,
    hmmer_program: str,
    id_regex: Optional[str],
) -> Dict[str, Set[str]]:
    """Parse HMMER domtblout files and return gene_id -> set(functions)."""
    matched: Dict[str, Set[str]] = defaultdict(set)

    # domtblout columns are whitespace separated. For hmmscan, query name is field 4
    # (0-based index 3). For hmmsearch, target name is field 1 (0-based index 0).
    gene_idx = 3 if hmmer_program == "hmmscan" else 0

    for result_file in result_files:
        function = function_name_from_file(result_file, strip_suffix)
        with result_file.open("r", encoding="utf-8", errors="replace") as handle:
            for line in handle:
                if not line.strip() or line.startswith("#"):
                    continue
                fields = line.strip().split()
                if len(fields) <= gene_idx:
                    continue
                gene_id = normalize_id(fields[gene_idx], id_regex)
                matched[gene_id].add(function)

    return matched


def ensure_output_paths(args: argparse.Namespace) -> None:
    """Create output directories and protect existing outputs unless --force is set."""
    for out_file in [args.out_cds, args.out_map, args.out_missing]:
        if out_file is None:
            continue
        out_path = Path(out_file)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        if out_path.exists() and not args.force:
            raise FileExistsError(f"Output file already exists: {out_path}. Use --force to overwrite.")


def extract_cds(
    cds_fasta: str,
    matched: Dict[str, Set[str]],
    out_cds: str,
    id_regex: Optional[str],
) -> Tuple[int, Set[str]]:
    """Stream through CDS FASTA, write matched records, and return count plus found IDs."""
    found: Set[str] = set()
    n_written = 0

    with open(out_cds, "w", encoding="utf-8") as out_handle:
        for record in SeqIO.parse(cds_fasta, "fasta"):
            normalized = normalize_id(record.id, id_regex)
            if normalized in matched:
                # Keep the original sequence, but standardize the output ID to the matched ID.
                # This makes downstream Bowtie2/SAM gene IDs consistent with gene_to_function.tsv.
                record.id = normalized
                record.name = normalized
                record.description = normalized
                SeqIO.write(record, out_handle, "fasta")
                found.add(normalized)
                n_written += 1

    return n_written, found


def write_mapping(matched: Dict[str, Set[str]], found: Set[str], out_map: str) -> int:
    """Write gene-to-function mapping for IDs found in the CDS FASTA."""
    n_rows = 0
    with open(out_map, "w", encoding="utf-8") as handle:
        handle.write("gene_id\tfunction\n")
        for gene_id in sorted(found):
            for function in sorted(matched[gene_id]):
                handle.write(f"{gene_id}\t{function}\n")
                n_rows += 1
    return n_rows


def write_missing(matched: Dict[str, Set[str]], found: Set[str], out_missing: str) -> int:
    """Write matched IDs that were not found in the CDS FASTA."""
    missing = sorted(set(matched) - found)
    with open(out_missing, "w", encoding="utf-8") as handle:
        for gene_id in missing:
            handle.write(f"{gene_id}\n")
    return len(missing)


def main() -> None:
    args = parse_args()
    if args.out_missing is None:
        args.out_missing = f"{args.out_map}.missing_ids.txt"

    ensure_output_paths(args)

    hmm_result_dir = Path(args.hmm_result_dir)
    if not hmm_result_dir.is_dir():
        sys.exit(f"ERROR: HMM result directory not found: {hmm_result_dir}")
    if not Path(args.cds_fasta).is_file():
        sys.exit(f"ERROR: CDS FASTA not found: {args.cds_fasta}")

    result_files = sorted(hmm_result_dir.glob(args.pattern))
    if not result_files:
        sys.exit(f"ERROR: No HMM result files matched {args.pattern!r} in {hmm_result_dir}")

    print(f"Parsing {len(result_files)} HMMER result files from: {hmm_result_dir}")
    matched = parse_domtblout(
        result_files=result_files,
        strip_suffix=args.strip_suffix,
        hmmer_program=args.hmmer_program,
        id_regex=args.id_regex,
    )
    print(f"Matched unique protein/gene IDs from HMMER output: {len(matched)}")

    print(f"Extracting matched CDS sequences from: {args.cds_fasta}")
    n_written, found = extract_cds(
        cds_fasta=args.cds_fasta,
        matched=matched,
        out_cds=args.out_cds,
        id_regex=args.id_regex,
    )

    n_map_rows = write_mapping(matched=matched, found=found, out_map=args.out_map)
    n_missing = write_missing(matched=matched, found=found, out_missing=args.out_missing)

    print("Done.")
    print(f"  CDS sequences written: {n_written}")
    print(f"  gene-to-function rows: {n_map_rows}")
    print(f"  matched IDs missing from CDS FASTA: {n_missing}")
    print(f"  Output CDS FASTA: {args.out_cds}")
    print(f"  Output mapping TSV: {args.out_map}")
    print(f"  Missing IDs file: {args.out_missing}")

    if n_written == 0:
        print(
            "WARNING: No CDS sequences were extracted. Check whether protein IDs in HMMER "
            "outputs match CDS FASTA IDs, or use --id-regex to normalize IDs.",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
