#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# Step 3: Map metagenomic reads to BileActome-positive CDSs using Bowtie2
#
# Purpose:
#   Build a Bowtie2 index for target CDS sequences generated by Step 2 and map
#   paired-end metagenomic reads to this functional CDS subset.
#
# Inputs:
#   1) --target-cds : FASTA file of matched nucleotide CDSs, e.g. target_cds.fa
#   2) --reads-dir  : directory containing paired-end clean reads
#
# Outputs:
#   1) Bowtie2 index files: <index-prefix>.*.bt2 or <index-prefix>.*.bt2l
#   2) SAM files: <out-dir>/<sample>.sam
#   3) Bowtie2 logs: <out-dir>/<sample>.bowtie2.log
#
# Features:
#   - Resumable: existing completed SAM files are skipped.
#   - Uses temporary files and atomic rename to avoid incomplete SAM outputs.
#   - Automatically skips Bowtie2 index construction if a complete index exists.
#   - Removes unfinished Bowtie2 index temporary files before rebuilding.
#   - By default, unmapped reads are not written to SAM (--no-unal) to reduce
#     file size. Use --keep-unal if downstream steps require unmapped records.
###############################################################################

usage() {
  cat <<'USAGE'
Usage:
  bash step3_bowtie2_mapping.sh \
    --target-cds /path/to/target_cds.fa \
    --reads-dir /path/to/clean_reads \
    --out-dir /path/to/bowtie2_map \
    [--index-prefix /path/to/target_cds_index] \
    [--threads 8] \
    [--r1-globs "*.fq1.gz,*_R1.clean.fq.gz"] \
    [--force] [--keep-unal]

Required arguments:
  --target-cds       FASTA file containing functionally annotated CDSs from Step 2.
  --reads-dir        Directory containing paired-end FASTQ files.
  --out-dir          Output directory for SAM files and Bowtie2 logs.

Optional arguments:
  --index-prefix     Bowtie2 index prefix. Default: <dirname(target-cds)>/target_cds_index
  --threads          Number of threads for Bowtie2. Default: 8
  --r1-globs         Comma-separated R1 filename glob patterns searched inside reads-dir.
                     Default: *.fq1.gz,*_R1.clean.fq.gz,*_R1*.fq.gz,*_R1*.fastq.gz,*_1.fq.gz,*_1.fastq.gz
  --force            Re-run mapping and overwrite existing SAM files.
  --keep-unal        Keep unmapped reads in SAM. Default: use --no-unal.
  -h, --help         Show this help message.

Example:
  bash scripts/step3_bowtie2_mapping.sh \
    --target-cds /data/project/target_cds.fa \
    --reads-dir /data/project/clean \
    --out-dir /data/project/bowtie2_map \
    --threads 16
USAGE
}

# ------------------------- default parameters -------------------------
TARGET_CDS=""
READS_DIR=""
OUT_DIR=""
INDEX_PREFIX=""
THREADS=8
R1_GLOBS="*.fq1.gz,*_R1.clean.fq.gz,*_R1*.fq.gz,*_R1*.fastq.gz,*_1.fq.gz,*_1.fastq.gz"
FORCE=0
KEEP_UNAL=0

# ------------------------- parse arguments ----------------------------
while [[ $# -gt 0 ]]; do
  case "$1" in
    --target-cds)
      TARGET_CDS="$2"; shift 2 ;;
    --reads-dir)
      READS_DIR="$2"; shift 2 ;;
    --out-dir)
      OUT_DIR="$2"; shift 2 ;;
    --index-prefix)
      INDEX_PREFIX="$2"; shift 2 ;;
    --threads)
      THREADS="$2"; shift 2 ;;
    --r1-globs)
      R1_GLOBS="$2"; shift 2 ;;
    --force)
      FORCE=1; shift ;;
    --keep-unal)
      KEEP_UNAL=1; shift ;;
    -h|--help)
      usage; exit 0 ;;
    *)
      echo "ERROR: Unknown argument: $1" >&2
      usage
      exit 1 ;;
  esac
done

# ------------------------- checks -------------------------------------
if [[ -z "${TARGET_CDS}" || -z "${READS_DIR}" || -z "${OUT_DIR}" ]]; then
  echo "ERROR: --target-cds, --reads-dir and --out-dir are required." >&2
  usage
  exit 1
fi

if [[ -z "${INDEX_PREFIX}" ]]; then
  INDEX_PREFIX="$(dirname "${TARGET_CDS}")/target_cds_index"
fi

command -v bowtie2 >/dev/null 2>&1 || { echo "ERROR: bowtie2 not found in PATH." >&2; exit 1; }
command -v bowtie2-build >/dev/null 2>&1 || { echo "ERROR: bowtie2-build not found in PATH." >&2; exit 1; }

[[ -s "${TARGET_CDS}" ]] || { echo "ERROR: target CDS FASTA not found or empty: ${TARGET_CDS}" >&2; exit 1; }
[[ -d "${READS_DIR}" ]] || { echo "ERROR: reads directory not found: ${READS_DIR}" >&2; exit 1; }
mkdir -p "${OUT_DIR}"

# ------------------------- helper functions ---------------------------
index_exists() {
  # Bowtie2 small index uses .bt2; large index uses .bt2l.
  # A complete index should contain the forward and reverse components.
  { [[ -f "${INDEX_PREFIX}.1.bt2" && -f "${INDEX_PREFIX}.rev.1.bt2" ]] || \
    [[ -f "${INDEX_PREFIX}.1.bt2l" && -f "${INDEX_PREFIX}.rev.1.bt2l" ]]; }
}

infer_r2() {
  local r1="$1"
  local r2="${r1}"
  r2="${r2/_R1.clean.fq.gz/_R2.clean.fq.gz}"
  r2="${r2/_R1.clean.fastq.gz/_R2.clean.fastq.gz}"
  r2="${r2/_R1.fq.gz/_R2.fq.gz}"
  r2="${r2/_R1.fastq.gz/_R2.fastq.gz}"
  r2="${r2/_R1_/_R2_}"
  r2="${r2/_R1./_R2.}"
  r2="${r2/.fq1.gz/.fq2.gz}"
  r2="${r2/.fastq1.gz/.fastq2.gz}"
  r2="${r2/_1.fq.gz/_2.fq.gz}"
  r2="${r2/_1.fastq.gz/_2.fastq.gz}"
  printf '%s\n' "${r2}"
}

sample_name_from_r1() {
  local fn
  fn="$(basename "$1")"
  fn="${fn%_R1.clean.fq.gz}"
  fn="${fn%_R1.clean.fastq.gz}"
  fn="${fn%_R1.fq.gz}"
  fn="${fn%_R1.fastq.gz}"
  fn="${fn%.fq1.gz}"
  fn="${fn%.fastq1.gz}"
  fn="${fn%_1.fq.gz}"
  fn="${fn%_1.fastq.gz}"
  printf '%s\n' "${fn}"
}

# ------------------------- build index --------------------------------
if index_exists; then
  echo "Skip Bowtie2 index build: existing complete index found at ${INDEX_PREFIX}"
else
  echo "Building Bowtie2 index for: ${TARGET_CDS}"
  # Clean interrupted index temporary files from previous failed builds.
  rm -f "${INDEX_PREFIX}"*.bt2.tmp "${INDEX_PREFIX}"*.bt2l.tmp 2>/dev/null || true
  bowtie2-build "${TARGET_CDS}" "${INDEX_PREFIX}"
fi

if ! index_exists; then
  echo "ERROR: Bowtie2 index is missing or incomplete after build: ${INDEX_PREFIX}" >&2
  echo "       Expected files such as ${INDEX_PREFIX}.1.bt2 and ${INDEX_PREFIX}.rev.1.bt2" >&2
  exit 1
fi

# ------------------------- collect R1 reads ----------------------------
echo "Collecting R1 reads from: ${READS_DIR}"
IFS=',' read -r -a GLOB_ARRAY <<< "${R1_GLOBS}"

shopt -s nullglob
R1_FILES=()
for pat in "${GLOB_ARRAY[@]}"; do
  # Trim surrounding spaces in pattern.
  pat="${pat#${pat%%[![:space:]]*}}"
  pat="${pat%${pat##*[![:space:]]}}"
  for f in "${READS_DIR}"/${pat}; do
    R1_FILES+=("${f}")
  done
done
shopt -u nullglob

# Remove duplicates while preserving order.
declare -A SEEN=()
UNIQUE_R1=()
for f in "${R1_FILES[@]}"; do
  if [[ -z "${SEEN[$f]+x}" ]]; then
    UNIQUE_R1+=("${f}")
    SEEN[$f]=1
  fi
done

if [[ ${#UNIQUE_R1[@]} -eq 0 ]]; then
  echo "ERROR: No R1 files found in ${READS_DIR}" >&2
  echo "       Tried patterns: ${R1_GLOBS}" >&2
  exit 1
fi

echo "Found ${#UNIQUE_R1[@]} R1 files. Start mapping..."

# ------------------------- mapping loop --------------------------------
BT2_UNAL_OPT="--no-unal"
if [[ "${KEEP_UNAL}" -eq 1 ]]; then
  BT2_UNAL_OPT=""
fi

for r1 in "${UNIQUE_R1[@]}"; do
  r2="$(infer_r2 "${r1}")"
  sample="$(sample_name_from_r1 "${r1}")"

  if [[ ! -f "${r2}" ]]; then
    echo "WARNING: Skip ${sample}; paired R2 file not found: ${r2}" >&2
    continue
  fi

  out_sam="${OUT_DIR}/${sample}.sam"
  out_tmp="${out_sam}.tmp"
  log_file="${OUT_DIR}/${sample}.bowtie2.log"
  log_tmp="${log_file}.tmp"
  done_flag="${OUT_DIR}/${sample}.done"

  if [[ "${FORCE}" -eq 0 && -f "${done_flag}" && -s "${out_sam}" ]]; then
    echo "Skip ${sample}: completed output already exists."
    continue
  fi

  if [[ "${FORCE}" -eq 0 && -s "${out_sam}" ]]; then
    echo "Skip ${sample}: existing non-empty SAM found; create missing done flag."
    touch "${done_flag}"
    continue
  fi

  echo "Mapping sample: ${sample}"
  rm -f "${out_tmp}" "${log_tmp}"

  # shellcheck disable=SC2086
  bowtie2 -x "${INDEX_PREFIX}" \
    -1 "${r1}" -2 "${r2}" \
    ${BT2_UNAL_OPT} \
    --threads "${THREADS}" \
    -S "${out_tmp}" \
    2> "${log_tmp}"

  if [[ ! -s "${out_tmp}" ]]; then
    echo "ERROR: Empty SAM output for sample ${sample}." >&2
    exit 1
  fi

  mv -f "${out_tmp}" "${out_sam}"
  mv -f "${log_tmp}" "${log_file}"
  touch "${done_flag}"
  echo "Done: ${sample}"
done

echo "All mapping tasks finished. Output directory: ${OUT_DIR}"
